from __future__ import annotations

BUY_LIKE_ACTIONS = {"BUILD", "ADD"}
SELL_LIKE_ACTIONS = {"REDUCE", "EXIT"}
PASSIVE_ACTIONS = {"HOLD"}

HOLDING_ACTION_FIELDS = [
    "trade_date",
    "symbol",
    "name",
    "sector",
    "board",
    "quantity",
    "available_quantity",
    "avg_cost",
    "prev_close",
    "last_price",
    "upper_limit",
    "lower_limit",
    "current_weight",
    "action_today",
    "target_weight",
    "stop_loss",
    "take_profit",
    "risk_level",
    "is_st",
    "suspended",
    "list_days",
    "reason",
    "last_trade_date",
    "t_plus_one_locked",
]

TECH_CANDIDATE_FIELDS = [
    "trade_date",
    "symbol",
    "name",
    "sector",
    "board",
    "last_price",
    "prev_close",
    "upper_limit",
    "lower_limit",
    "rule_pass",
    "tech_score",
    "momentum_score",
    "breakout_score",
    "liquidity_score",
    "turnover_rate",
    "relative_volume",
    "amount",
    "near_upper_limit",
    "is_st",
    "suspended",
    "list_days",
    "trigger_tags",
]

AI_INSIGHT_FIELDS = [
    "trade_date",
    "symbol",
    "name",
    "sector",
    "board",
    "action_hint",
    "confidence",
    "tech_score",
    "news_event_score",
    "fundamental_score",
    "combined_score",
    "thesis",
    "risk_flags",
    "source",
    "analyst_failed",
]

ORDER_CANDIDATE_FIELDS = [
    "trade_date",
    "order_id",
    "symbol",
    "name",
    "sector",
    "board",
    "action",
    "w_ai",
    "w_candidate",
    "target_weight",
    "entry_price",
    "stop_loss_price",
    "take_profit_price",
    "reduce_price",
    "exit_price",
    "reason",
    "source",
    "confidence",
]

TRADE_PLAN_FIELDS = [
    "trade_date",
    "order_id",
    "symbol",
    "name",
    "sector",
    "board",
    "action",
    "w_ai",
    "w_candidate",
    "target_weight",
    "w_final",
    "status",
    "cap_hit_reason",
    "risk_mode",
    "entry_price_final",
    "stop_loss_price_final",
    "take_profit_price_final",
    "reduce_price_final",
    "exit_price_final",
    "reason",
]

SIM_FILL_FIELDS = [
    "trade_date",
    "order_id",
    "symbol",
    "name",
    "board",
    "action",
    "planned_price",
    "fill_price",
    "price_deviation_bps",
    "quantity",
    "filled_amount",
    "commission",
    "stamp_duty",
    "transfer_fee",
    "total_fee",
    "status",
    "note",
]

POSITION_FIELDS = [
    "trade_date",
    "symbol",
    "name",
    "sector",
    "board",
    "quantity",
    "available_quantity",
    "avg_cost",
    "prev_close",
    "last_price",
    "upper_limit",
    "lower_limit",
    "market_value",
    "weight",
    "unrealized_pnl_pct",
    "is_st",
    "suspended",
    "last_trade_date",
]

NAV_FIELDS = [
    "trade_date",
    "cash",
    "market_value",
    "total_equity",
    "trading_fees",
    "daily_return",
    "cum_return",
    "max_drawdown",
    "filled_order_count",
]
